config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
  end
  
  # ユーザー
  resources 'users', except: [:edit] do
    collection do
      get 'credit_register'
      get 'edit'
      get 'logout'
      get 'edit_profile'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'mercaris#index'

  # products
  resources 'products' do
    resources 'purchase' ,only: [:new,:create,:index]
    collection do
      get 'purchase_confirmation'
      get 'products/bigcategory'   => 'products#bigcategory',   defaults:{format: 'json'}
      get 'products/smallcategory' => 'products#smallcategory', defaults:{format: 'json'}
      get 'products/size'          => 'products#size',          defaults:{format: 'json'}
    end
  end

  # search
  resources 'search',only: :index

  resources :signin ,only: [:new,:create,:index]


  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'
      post 'registration' => 'signup#first_validation'
      get 'sms_authentication' 
      post 'sms_authentication' => 'signup#sms_post'
      get 'sms_confirmation' 
      post 'sms_confirmation' => 'signup#sms_check'
      get 'address' 
      post 'address' => 'signup#second_validation'
      get 'creditcard'
      get 'done'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise   :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_one  :profile,       dependent: :destroy
  has_one  :creditcard,    dependent: :destroy
  has_many :products,      dependent: :destroy
  has_many :buyer_trades,  class_name: "Trade", foreign_key: "buyer_id",  dependent: :destroy
  has_many :seller_trades, class_name: "Trade", foreign_key: "seller_id", dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  PASSWORD_VALIDATION = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,128}+\z/i
  validates :email,                 presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  validates :password,              presence: true, length: {minimum: 7, maximum: 128},    format: { with: PASSWORD_VALIDATION }
  validates :password_confirmation, presence: true, length: {minimum: 7, maximum: 128}
  validates :nickname,              presence: true, length: {maximum: 20}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_login_form_unless_signed_in
  before_action :set_categories
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
    @user = current_user
    @categories      = CategoryIndex.all
    @bigcategories   = Bigcategory.all
    @smallcategories = Smallcategory.all
  end

  def delete
  end

  def credit_register
  end

  def logout
  end

  private

  def set_categories
    @categories      = CategoryIndex.all
    @bigcategories   = Bigcategory.all
    @smallcategories = Smallcategory.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/credit_register.html.haml
= render "layouts/main-header"
-# パンくず最後のページだけspan、リンクはaタグを使用する。
-content_for :current_page do
  %span.current_page
    = link_to users_path do
      マイページ
    %i.fa.fa-chevron-right
    %span.current_page__now
      支払い方法
= render "layouts/breadcrumbs"
.user-mypage-wrapper
  .user-mypage-wrapper__main
    .user-mypage-wrapper__main__credit
      .user-mypage-wrapper__main__credit__title
        支払い方法
      .user-mypage-wrapper__main__credit__content
        .user-mypage-wrapper__main__credit__content__index
          %p クレジットカード一覧
        = link_to '#',class: 'submit-btn submit-btn-red user-mypage-wrapper__main__credit__content__btn' do
          %i.far.fa-credit-card
          %span クレジットカードを追加する
        .user-mypage-wrapper__main__credit__content__description
          = link_to "" do
            支払い方法について
            %i.fa.fa-chevron-right
  = render "layouts/user-navi"  

-# footer
= render "layouts/footer-advertisement"
= render "layouts/footer-black"

-# 右下の赤いカメラ
=render "layouts/bottom-camera"

app/views/users/edit.html.haml
= render "layouts/main-header"
-content_for :current_page do
  %span.current_page
    = link_to users_path do
      マイページ
    %i.fa.fa-chevron-right
    %span.current_page__now
      本人情報の登録
= render "layouts/breadcrumbs"
.user-mypage-wrapper
  .user-mypage-wrapper__main
    .user-mypage-wrapper__main__credit
      .user-mypage-wrapper__main__credit__title
        本人情報の登録
      .user-mypage-wrapper__main__box__contents
        .user-mypage-wrapper__main__box__contents__notice
          お客さまの本人情報をご登録ください。
          %br
          登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          = link_to "" do
            本人確認書類のアップロードについて
            %i.fa.fa-chevron-right
        .signup-form-container.registration-form__first-container.mypage-form-container
          .signup-form-container__title
            = label :name, 'お名前', class: 'signup-label'
          = current_user.profile.post_family_name + current_user.profile.post_personal_name
        .signup-form-container.mypage-form-container
          .signup-form-container__title
            = label :name, 'お名前カナ', class: 'signup-label'
          = current_user.profile.post_family_name_kana + current_user.profile.post_personal_name_kana
        .signup-form-container.mypage-form-container
          .signup-form-container__title
            = label :name, '生年月日', class: 'signup-label'
          = current_user.profile.birthyear.to_s + "/" + current_user.profile.birthmonth.to_s + "/" + current_user.profile.birthday.to_s
        .signup-form-container.mypage-form-container
          .signup-form-container__title
            = label :postal_code, '郵便番号', class: 'signup-label'
            %span.signup-form-container__span.span-optional 任意
          = text_field :user, :postal_code, placeholder: '例）123-4567', class: 'default-input'
        .signup-form-container.mypage-form-container
          .signup-form-container__title
            = label :postal_code, '都道府県', class: 'signup-label'
            %span.signup-form-container__span.span-optional 任意
          .select-wrap.select-wrap__full
            = select :user,:prefecture,Prefecture.pluck(:name).unshift('--'),{},{class: 'default-select default-select__full'}
            %i.select-arrow.fas.fa-chevron-down
        .signup-form-container.mypage-form-container
          .signup-form-container__title
            = label :city, '市区町村', class: 'signup-label'
            %span.signup-form-container__span.span-optional 任意
          = text_field :user, :city, placeholder: '例）横浜市緑区', class: 'default-input'
        .signup-form-container.mypage-form-container
          .signup-form-container__title
            = label :address, '番地', class: 'signup-label'
            %span.signup-form-container__span.span-optional 任意
          = text_field :user, :address, placeholder: '例）青山1-1-1', class: 'default-input'
        .signup-form-container.mypage-form-container
          .signup-form-container__title
            = label :building, '建物名', class: 'signup-label'
            %span.signup-form-container__span.span-optional 任意
          = text_field :user, :building, placeholder: '例）柳ビル103', class: 'default-input'
        %input.submit-btn.submit-btn-red{type: 'submit',value: '登録する'}
        .content-end
          = link_to "" do
            本人情報の登録について
            %i.fa.fa-chevron-right
  = render "layouts/user-navi"
-# footer
= render "layouts/footer-advertisement"
= render "layouts/footer-black"

-# 右下の赤いカメラ
=render "layouts/bottom-camera"

app/views/users/edit_profile.html.haml
= render "layouts/main-header"
-# パンくず最後のページだけspan、リンクはaタグを使用する。
-content_for :current_page do
  %span.current_page
    = link_to users_path do
      マイページ
    %i.fa.fa-chevron-right
    %span.current_page__now
      プロフィール
= render "layouts/breadcrumbs"
.user-mypage-wrapper
  .user-mypage-wrapper__main
    .user-mypage-wrapper__main__profile-edit
      .user-mypage-wrapper__main__profile-edit__title
        プロフィール
      %form.user-mypage-wrapper__main__profile-edit__content
        .user-mypage-wrapper__main__profile-edit__content__icon
          = image_tag src="https://static.mercdn.net/images/member_photo_noimage_thumb.png", size: "60x60", class: "user-mypage-wrapper__main__profile-edit__content__icon__img"
          %input.user-mypage-wrapper__main__profile-edit__content__icon__input-default{placeholder: "例)AYA☆セール中", type: "text", value: current_user.nickname, name: "nickname"}

        .user-mypage-wrapper__main__profile-edit__content__index
          %textarea.user-mypage-wrapper__main__profile-edit__content__index__text{placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", value: "", name: "introduction"}
          = link_to '#',class: 'submit-btn submit-btn-red user-mypage-wrapper__main__profile-edit__content__index__btn' do
            %span 変更する
        
  = render "layouts/user-navi"  

-# footer
= render "layouts/footer-advertisement"
= render "layouts/footer-black"

-# 右下の赤いカメラ
=render "layouts/bottom-camera"

app/views/users/logout.html.haml
= render "layouts/main-header"
-content_for :current_page do
  %span.current_page
    = link_to "users_show_path" do
      マイページ
    %i.fa.fa-chevron-right
    %span.current_page__now
      ログアウト
= render "layouts/breadcrumbs"
.user-mypage-wrapper
  .user-mypage-wrapper__main
    .user-mypage-wrapper__main__box
      .user-mypage-wrapper__main__box__title
        %form.user-mypage-wrapper__main__box__title__inner
          .user-mypage-wrapper__main__box__title__inner__content
            = link_to 'ログアウト',current_user_destroy_path,method: :delete,class: "user-mypage-wrapper__main__box__title__inner__content__btn submit-btn submit-btn-red"
  = render "layouts/user-navi"  

-# footer
= render "layouts/footer-advertisement"
= render "layouts/footer-black"

-# 右下の赤いカメラ
=render "layouts/bottom-camera"

app/views/users/show.html.haml
= render "layouts/main-header"
-content_for :current_page do
  %span.current_page
    %span.current_page__now
      マイページ
= render "layouts/breadcrumbs"
.user-mypage-wrapper
  .user-mypage-wrapper__main
    .user-mypage-wrapper__main__profile
      .user-mypage-wrapper__main__profile__container
        .user-mypage-wrapper__main__profile__container__image
          = image_tag "https://static.mercdn.net/images/member_photo_noimage_thumb.png", "alt width":"60", height:"60"
        .user-mypage-wrapper__main__profile__container__content.bold
          %h2 
            = @user.nickname
        .user-mypage-wrapper__main__profile__container__status
          .user-mypage-wrapper__main__profile__container__status__content
            .user-mypage-wrapper__main__profile__container__status__content__name
              評価
            .user-mypage-wrapper__main__profile__container__status__content__number.bold
              = rand(100)
          .user-mypage-wrapper__main__profile__container__status__content
            .user-mypage-wrapper__main__profile__container__status__content__name__products
              出品数
            .user-mypage-wrapper__main__profile__container__status__content__number.bold
              = @user.products.count
      .user-mypage-wrapper__main__profile__contents.tabs
        .tabs
          %input#notice.user-mypage-wrapper__main__profile__contents__notice{checked: "checked", name: "tab_item", type: "radio"}/
          %label.tab_item{for: "notice"} お知らせ
          %input#task{name: "tab_item", type: "radio"}/
          %label.tab_item.user-mypage-wrapper__main__profile__contents__task{for: "task"} やることリスト
          #notice_content.tab_content
            .tab_content_description__content
              .tab_content_description__content__image
                = image_tag "//static.mercdn.net/images/mercari_profile.png", alt:"", height:"48"
              .tab_content_description__content__body
                .tab_content_description__content__body__message
                  message1
                .tab_content_description__content__body__time
                  %i.far.fa-clock
                  0日前(秒前、分前、時間前)
              .tab_content_description__content__arrow
                %i.fas.fa-chevron-right
            .tab_content_description__content
              .tab_content_description__content__image
                = image_tag "//static.mercdn.net/images/mercari_profile.png", alt:"", height:"48"
              .tab_content_description__content__body
                .tab_content_description__content__body__message
                  message1
                .tab_content_description__content__body__time
                  %i.far.fa-clock
                  0日前(秒前、分前、時間前)
              .tab_content_description__content__arrow
                %i.fas.fa-chevron-right
            .tab_content_description__content
              .tab_content_description__content__image
                = image_tag "//static.mercdn.net/images/mercari_profile.png", alt:"", height:"48"
              .tab_content_description__content__body
                .tab_content_description__content__body__message
                  message1
                .tab_content_description__content__body__time
                  %i.far.fa-clock
                  0日前(秒前、分前、時間前)
              .tab_content_description__content__arrow
                %i.fas.fa-chevron-right
            .tab_content_description__content
              .tab_content_description__content__image
                = image_tag "//static.mercdn.net/images/mercari_profile.png", alt:"", height:"48"
              .tab_content_description__content__body
                .tab_content_description__content__body__message
                  message1
                .tab_content_description__content__body__time
                  %i.far.fa-clock
                  0日前(秒前、分前、時間前)
              .tab_content_description__content__arrow
                %i.fas.fa-chevron-right
            .tab_content_description__content
              .tab_content_description__content__image
                = image_tag "//static.mercdn.net/images/mercari_profile.png", alt:"", height:"48"
              .tab_content_description__content__body
                .tab_content_description__content__body__message
                  message1
                .tab_content_description__content__body__time
                  %i.far.fa-clock
                  0日前(秒前、分前、時間前)
              .tab_content_description__content__arrow
                %i.fas.fa-chevron-right
            .tab_content_description__content__back
              .tab_content_description__content__back__message
                %p 一覧を見る
          #task_content.tab_content
            .tab_content_description__task.nothing_image
              現在やることリストはありません。
    .user-mypage-wrapper__main__products
      .user-mypage-wrapper__main__products__title
        %h2 購入した商品
      .tabs2
        %input#trading{checked: "checked", name: "tab_item2", type: "radio"}/
        %label.tab_item2{for: "trading"} 取引中
        %input#traded{name: "tab_item2", type: "radio"}/
        %label.tab_item2{for: "traded"} 過去の取引
        #trading_content.tab_content
          .tab_content_description.nothing_image
            %p 現在取引している商品がありません。
        #traded_content.tab_content
          .tab_content_description.nothing_image
            %p 過去に取引した商品がありません。
  = render "layouts/user-navi"  

-# footer
= render "layouts/footer-advertisement"
= render "layouts/footer-black"

-# 右下の赤いカメラ
=render "layouts/bottom-camera"