config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
  end
  
  # ユーザー
  resources 'users', except: [:edit] do
    collection do
      get 'credit_register'
      get 'edit'
      get 'logout'
      get 'edit_profile'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'mercaris#index'

  # products
  resources 'products' do
    resources 'purchase' ,only: [:new,:create,:index]
    collection do
      get 'purchase_confirmation'
      get 'products/bigcategory'   => 'products#bigcategory',   defaults:{format: 'json'}
      get 'products/smallcategory' => 'products#smallcategory', defaults:{format: 'json'}
      get 'products/size'          => 'products#size',          defaults:{format: 'json'}
    end
  end

  # search
  resources 'search',only: :index

  resources :signin ,only: [:new,:create,:index]


  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'
      post 'registration' => 'signup#first_validation'
      get 'sms_authentication' 
      post 'sms_authentication' => 'signup#sms_post'
      get 'sms_confirmation' 
      post 'sms_confirmation' => 'signup#sms_check'
      get 'address' 
      post 'address' => 'signup#second_validation'
      get 'creditcard'
      get 'done'
    end
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  layout 'form_layout'
  before_action :redirect_to_root_user_signed_in

  def new
    @signin = Signin.new
  end

  def index
    redirect_to new_signin_path
  end

  def create
    @signin = Signin.new(email: signin_params[:email], password: signin_params[:password])
    #バリデーションエラーを事前に取得
    check_valid = @signin.valid?
    unless verify_recaptcha(@signin) && check_valid
      render "signin/new"
    else
      @user = User.find_by_email(@signin.email)
      if @user.present? && @user.valid_password?(@signin.password)
        sign_in @user unless user_signed_in?
        redirect_to root_path
      else
        session[:signin_error] = "メールアドレスまたはパスワードが違います"
        render "signin/new"
      end
    end
  end

  private

  def signin_params
    params.require(:signin).permit(:email, :password)
  end

end

app/views/signin/new.html.haml
- content_for(:html_title) {'ログイン'}
= render partial: 'signup/simple-header'
.signin-container
  .signin-top
    .signin-top__signup
      %p.signin-top__signup__text アカウントをお持ちでない方はこちら
      = link_to '新規会員登録',registration_signup_index_path,class: 'submit-btn signin-top__signup--btn'
    .signin-top__form
      .signin-top__form__sns
        = link_to root_path,class: 'submit-btn signin-top__form__sns__facebook' do
          %i.fab.fa-facebook-square.signin-top__form--icon.signin-top__form--facebook
          = 'Facebookでログイン'
        = link_to root_path,class: 'submit-btn signin-top__form__sns__google' do
          %i.fab.fa-google.signin-top__form--icon.signin-top__form--google
          = 'Googleでログイン'
      .signin-top__form__normal
        = form_for @signin,url: signin_index_path,method: :post do |f|
          = f.email_field :email, placeholder: 'メールアドレス',class: 'signin-top__form__normal--email default-input'
          - if judge_blank(@signin,:email)
            .input-error メールアドレスを入力してください
          - elsif judge_format(@signin,:email)
            .input-error フォーマットが不適切です
          = f.password_field :password, placeholder: 'パスワード',class: 'signin-top__form__normal--password default-input'
          - if judge_blank(@signin,:password)
            .input-error パスワードを入力してください
          - if judge_length_short(@signin,:password,7) || judge_length_long(@signin,:password,128)
            .input-error パスワードは7文字以上128文字以下で入力してください
          .signup-form-container.recaptcha-container
            - if judge_recaptcha(@signin)
              .recaptcha-error-border
            = recaptcha_tags
            - if judge_recaptcha(@signin)
              .input-error 選択してください
          =f.submit "ログイン",class: "submit-btn submit-btn-red"
        = link_to 'パスワードをお忘れの方', '',class: 'signin-top__form__normal--link default-link-text'
= render partial: 'signup/simple-footer'