config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
  end
  
  # ユーザー
  resources 'users', except: [:edit] do
    collection do
      get 'credit_register'
      get 'edit'
      get 'logout'
      get 'edit_profile'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'mercaris#index'

  # products
  resources 'products' do
    resources 'purchase' ,only: [:new,:create,:index]
    collection do
      get 'purchase_confirmation'
      get 'products/bigcategory'   => 'products#bigcategory',   defaults:{format: 'json'}
      get 'products/smallcategory' => 'products#smallcategory', defaults:{format: 'json'}
      get 'products/size'          => 'products#size',          defaults:{format: 'json'}
    end
  end

  # search
  resources 'search',only: :index

  resources :signin ,only: [:new,:create,:index]


  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'
      post 'registration' => 'signup#first_validation'
      get 'sms_authentication' 
      post 'sms_authentication' => 'signup#sms_post'
      get 'sms_confirmation' 
      post 'sms_confirmation' => 'signup#sms_check'
      get 'address' 
      post 'address' => 'signup#second_validation'
      get 'creditcard'
      get 'done'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # バリデーション
  validates :title,               length:    {maximum: 40},         presence: true
  validates :text,                length:    {maximum: 1000},       presence: true
  validates :category_index_id,   exclusion: {in: %w(---) }
  validates :fresh_status ,       exclusion: {in: %w(---) }
  validates :deliver_way,         exclusion: {in: %w(---)}
  validates :deliver_person,      exclusion: {in: %w(---)}
  validates :from_area,           exclusion: {in: %w(都道府県)}
  validates :deliver_leadtime,    exclusion: {in: %w(---)}
  validates :price,               numericality: [greater_than: 300, less_than: 10000000 ]

  # アソシエーション
  belongs_to :user,              optional:true
  belongs_to :brand,             optional:true
  has_many :product_images,      dependent: :delete_all
  accepts_nested_attributes_for :product_images
  has_one :trade
  
  # カテゴリ関係
  has_one :category_index
  has_one :bigcategory
  has_one :smallcategory
  has_one :size
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :redirect_to_login_form_unless_signed_in, except: :show
  before_action :get_product, only: [:show, :destroy, :destroy, :edit, :update]
  before_action :set_categories, only: [:show]
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.category_index_id != nil && params[:product_image].present? && params[:product_image][:image].length <= 10 && @product.save
      params[:product_image][:image].each do |image|
        @product.product_images.create(image: image, product_id: @product.id)
      end
      redirect_to root_path
      return false
    else
      @product.valid?
      if params[:product_image].present? == false
        @product.errors.messages[:image] = ["image is blank"]
      elsif params[:product_image][:image].length > 10
        @product.errors.messages[:image] = ["image is too many"]
      end 
      @product.errors.messages[:category_index_id] = ["is reserved"] if @product.category_index_id == nil
      render json: {errors: @product.errors.messages},status: 422
    end
  end

  def show
    @products = Product.all.limit(6)
    @category_name = CategoryIndex.find(@product.category_index_id).name
    @bigcategory_name = Bigcategory.find(@product.bigcategory_id).name
    @smallcategory_name= Smallcategory.find(@product.smallcategory_id).name
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  def bigcategory
    respond_to do |format|
      format.json{@bigcategory_options = Bigcategory.where(category_index: params[:category_id])}
    end
  end

  def smallcategory
    respond_to do |format|
      format.json{@smallcategory_options = Smallcategory.where(bigcategory: params[:bigcategory_id])}
    end
  end

  def size
    respond_to do |format|
      format.json{@size_options = Smallcategory.find_by(id: params[:smallcategory_id]).smallcategories_has_sizes}
    end
  end

  def edit
  end

  def update
    if @product.user_id == current_user.id && @product.update(product_params)
      redirect_to root_path
    else
      render 'products/edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :text, :category_index_id ,:fresh_status, :deliver_way, :deliver_person, :from_area, :deliver_leadtime, :price, :deliver_day,:bigcategory_id, :smallcategory_id, :size_id)
  end

  def get_product
    @product = Product.find(params[:id])
  end

  def set_categories
    @categories      = CategoryIndex.all
    @bigcategories   = Bigcategory.all
    @smallcategories = Smallcategory.all
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_index.html.haml
.main__products
  .main__products__product
    .main__products__product__header
      テックエキスパート新着アイテム
      .main__products__product__header__next
        = link_to "#" do
          もっと見る
          %i.fa.fa-chevron-right
    .main__products__product__contents
      - @products.each do |product|
        .main__products__product__contents__content.effect-fade
          = link_to "/products/#{product.id}" do
            .main__products__product__contents__content__image
              -# ※carrierwaveなどで画像を正方形に加工する必要あり※
              = image_tag product.product_images.find_by(product_id: product.id).image_url
              .main__products__product__contents__content__image__price
                = "¥#{product.price}"
            .main__products__product__contents__content__name
              %p= "#{product.title}"

app/views/products/edit.html.haml
.sell-container
  .signup-container
    = render partial: '/signup/simple-header'
    = form_for @product, url:product_path ,method: :patch do |f|
      .signup-top
        %h2.signup-header
          商品の情報を入力
      .sell-upload-form
        -# 画像アップロード
        .sell-upload-form__image.sell-container-all-padding.container-border-top
          %p
            = label :image, '出品画像',class: 'sell-upload-label'
            %span.signup-form-container__span.span-need
              必須
          .upload-box
            %ul#preview
          - if judge_blank(@product, :product_images)
            .input-error 画像がありません
        -# 商品名、商品の説明
        .signup-form-container.registration-form__first-container.sell-container-all-padding.container-border-top
          .signup-form-container__title
            %p
              = label :title, '商品名',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
          = f.text_field :title, placeholder: '商品名（必須40文字まで）', class: 'default-input sell-input'
          - if judge_blank(@product, :title)
            .input-error 入力してください
          - if judge_length_long(@product, :title, 40)
            .input-error 40文字以下で入力してください
        .signup-form-container.registration-form__first-container.sell-container-side-padding
          .signup-form-container__title
            %p
              = label :text, '商品の説明',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
          = f.text_area :text, placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）　2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。 ", class: 'default-input sell-input-area'
          - if judge_blank(@product, :text)
            .input-error 入力してください
          - if judge_length_long(@product, :title, 1000)
            .input-error 1000文字以下で入力してください
        -# 商品の明細
        .sell-container-all-padding.container-border-top.flex
          .sell-container-left
            商品の詳細
          .sell-container-right
            %p
              = label :category_index, 'カテゴリー',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.collection_select(:category_index_id, CategoryIndex.all,:id,:name,{prompt:"---"}, {class: 'default-select sell-select-box'})
              %i.select-arrow.fas.fa-chevron-down
            - if judge_blank(@product, :category_index_id)
              .input-error 選択してください

            -# ここにbigcategory,smallcategoryを挿入する

            %p.margin-2rem
              = label :fresh_status, '商品の状態',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select:fresh_status, ProductFreshness.pluck(:status).unshift('---'),{},{class: 'default-select sell-select-box sell-input'}
              %i.select-arrow.fas.fa-chevron-down
            - if judge_exception(@product, :fresh_status)
              .input-error 選択してください
        -# 配送について
        .sell-container-all-padding.container-border-top.flex
          .sell-container-left
            %p
              配送について
              = link_to "" do
                %i.fas.fa-question-circle.link-space-reset
          .sell-container-right
            %p
              = label :deliver_person, '配送料の負担',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :deliver_person, DeliverFee.pluck(:fee).unshift('---'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            - if judge_exception(@product, :deliver_person)
              .input-error 選択してください
            %p.margin-2rem
              = label :deliver_leadtime, '配達の方法',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :deliver_way,DeliverWay.pluck(:way).unshift('---'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            - if judge_exception(@product, :deliver_way)
              .input-error 選択してください
            %p.margin-2rem
              = label :from_area, '発送元の地域',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :from_area ,Prefecture.pluck(:name).unshift('都道府県', '未定'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            - if judge_exception(@product, :from_area)
              .input-error 選択してください
            %p.margin-2rem
              = label :deliver_leadtime, '発送までの日数',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :deliver_leadtime,DeliverDay.pluck(:days).unshift('---'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            - if judge_exception(@product, :deliver_leadtime)
              .input-error 選択してください
        -# 販売価格
        .sell-container-all-padding.container-border-top.flex
          .sell-container-left.link-space-reset
            %p
              販売価格
              %span.link-space-reset (300~9,999,999)
              = link_to "" do
                %i.fas.fa-question-circle
          .sell-container-right
            .sell-container-right__price-wrapper
              %p
                = label :price, '価格',class: 'signup-label' do
                  価格
                  %span.signup-form-container__span.span-need 必須
              .sell-container-right__price-wrapper__input
                %p
                  ¥
                  = f.text_field :price, placeholder: "例：300", id:"product_price", class: 'default-input price ', style:"text-align:right"
            - if @product.errors.details[:price].present?
              .input-error 300以上9999999以下で入力してください
            .sell-container-right__price-fee
              .sell-container-right__price-fee__text
                %p
                  販売手数料(10%)
              .sell-container-right__price-fee__price
                %p#price_fee
                  ー
            .sell-container-right__price-benefit
              %h2
                販売利益
              %h2#price_benefit
                ー
        -# 説明、出品ボタン
        .sell-container-all-padding.container-border-top
          .sell-container-submit
            = f.submit value: "変更する",class: 'submit-btn submit-btn-red user-mypage-wrapper__main__credit__content__btn sell-container-submit__btn'
          .sell-container-back
            %p
              = link_to product_path,class: 'submit-btn submit-btn-gray user-mypage-wrapper__main__credit__content__btn sell-container-back__btn' do
                %span キャンセル
  = render 'signup/simple-footer'

app/views/products/new.html.haml
.sell-container
  .signup-container
    = render partial: '/signup/simple-header'
    = form_for @product, html:{class: "sell-form"} do |f|
      .signup-top
        %h2.signup-header
          商品の情報を入力
      .sell-upload-form
        -# 画像アップロード
        .sell-upload-form__image.sell-container-all-padding.container-border-top
          %p
            = label :image, '出品画像',class: 'sell-upload-label'
            %span.signup-form-container__span.span-need
              必須
          .upload-box
            %ul#preview
              %p.sell-upload-form__image--images-container
                ドラッグアンドドロップして
                %br
                ファイルをアップロード
          .input-error#product_image_error
        -# 商品名、商品の説明
        .signup-form-container.registration-form__first-container.sell-container-all-padding.container-border-top
          .signup-form-container__title
            %p
              = label :title, '商品名',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
          = f.text_field :title, placeholder: '商品名（必須40文字まで）', class: 'default-input sell-input'
          .input-error#product_title_error
        .signup-form-container.registration-form__first-container.sell-container-side-padding
          .signup-form-container__title
            %p
              = label :text, '商品の説明',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
          = f.text_area :text, placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）　2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。 ", class: 'default-input sell-input-area'
          .input-error#product_text_error
        -# 商品の明細
        .sell-container-all-padding.container-border-top.flex
          .sell-container-left
            商品の詳細
          .sell-container-right
            %p
              = label :category_index, 'カテゴリー',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .category_wrapper
              .select-wrap.category_index_wrapper
                = f.collection_select(:category_index_id, CategoryIndex.all,:id,:name,{prompt:"---"}, {class: 'default-select sell-select-box select_category_index'})
                %i.select-arrow.fas.fa-chevron-down
              .input-error#product_category_index_id_error

            -# ここにbigcategory,smallcategoryを挿入する

            %p.margin-2rem
              = label :fresh_status, '商品の状態',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select:fresh_status, ProductFreshness.pluck(:status).unshift('---'),{},{class: 'default-select sell-select-box sell-input'}
              %i.select-arrow.fas.fa-chevron-down
            .input-error#product_fresh_status_error
        -# 配送について
        .sell-container-all-padding.container-border-top.flex
          .sell-container-left
            %p
              配送について
              = link_to "" do
                %i.fas.fa-question-circle.link-space-reset
          .sell-container-right
            %p
              = label :deliver_person, '配送料の負担',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :deliver_person, DeliverFee.pluck(:fee).unshift('---'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            .input-error#product_deliver_person_error
            %p.margin-2rem
              = label :deliver_leadtime, '配達の方法',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :deliver_way,DeliverWay.pluck(:way).unshift('---'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            .input-error#product_deliver_way_error
            %p.margin-2rem
              = label :from_area, '発送元の地域',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :from_area ,Prefecture.pluck(:name).unshift('都道府県', '未定'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            .input-error#product_from_area_error
            %p.margin-2rem
              = label :deliver_leadtime, '発送までの日数',class: 'signup-label'
              %span.signup-form-container__span.span-need 必須
            .select-wrap
              = f.select :deliver_leadtime,DeliverDay.pluck(:days).unshift('---'),{},{class: 'default-select select-wrap__sell-select-box'}
              %i.select-arrow.fas.fa-chevron-down
            .input-error#product_deliver_leadtime_error
        -# 販売価格
        .sell-container-all-padding.container-border-top.flex
          .sell-container-left.link-space-reset
            %p
              販売価格
              %span.link-space-reset (300~9,999,999)
              = link_to "" do
                %i.fas.fa-question-circle
          .sell-container-right
            .sell-container-right__price-wrapper
              %p
                = label :price, '価格',class: 'signup-label' do
                  価格
                  %span.signup-form-container__span.span-need 必須
              .sell-container-right__price-wrapper__input
                %p
                  ¥
                  = f.text_field :price, placeholder: "例：300", id:"product_price", class: 'default-input price ', style:"text-align:right"
            .input-error#product_price_error
            .sell-container-right__price-fee
              .sell-container-right__price-fee__text
                %p
                  販売手数料(10%)
              .sell-container-right__price-fee__price
                %p#price_fee
                  ー
            .sell-container-right__price-benefit
              %h2
                販売利益
              %h2#price_benefit
                ー
        -# 説明、出品ボタン
        .sell-container-all-padding.container-border-top
          .sell-container-description
            %p
              = link_to "禁止されている出品", ""
              、
              = link_to "行為", ""
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "偽ブランドの販売", "" 
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              = link_to "加盟店規約", ""
              に同意したことになります。
          .sell-container-submit
            = f.submit "出品する",class: 'submit-btn submit-btn-red user-mypage-wrapper__main__credit__content__btn sell-container-submit__btn'
          .sell-container-back
            %p
              = link_to root_path,class: 'submit-btn submit-btn-gray user-mypage-wrapper__main__credit__content__btn sell-container-back__btn' do
                %span もどる
  = render 'signup/simple-footer'

app/views/products/show.html.haml
= render "/layouts/main-header"

.container
  .container__product-details
    %h1.container__product-details__product-name
      = @product.title
    .container__product-details__main
      .container__product-details__main__images
        .container__product-details__main__images__display
          - if @product.sell_status == "SOLD"
            .badge.sold
              SOLD
          -elsif @product.sell_status == "公開停止中"
            .badge.stop
              公開停止中
          %ul.container__product-details__main__images__display__up
            - @product.product_images.each do |product_image|
              %li.container__product-details__main__images__display__up__slide-image
                = image_tag product_image.image_url, size: "300x300"
          %ul.container__product-details__main__images__display__down
            - @product.product_images.each do |product_image|
              %li.container__product-details__main__images__display__down__thumbnail-image
                = image_tag product_image.image_url, size: "60x60"
      %table.container__product-details__main__detail
        %tbody
          %tr
            %th
              出品者
            %td
              = link_to @product.user.nickname, ""
              %div.evaluation
                %div
                  %i.far.fa-laugh
                  = rand(100)
                %div
                  %i.fas.far.fa-meh
                  = rand(100)
                %div
                  %i.far.fa-sad-tear
                  = rand(100)
          %tr
            %th
              カテゴリー
            %td.category
              = link_to "" do
                .category
                  %span
                    = @category_name
              = link_to "" do
                .category
                  %i.fas.fa-chevron-right
                    %span
                      = @bigcategory_name
              = link_to "" do
                .category
                  %i.fas.fa-chevron-right
                    %span
                      = @smallcategory_name
          %tr
            %th
              ブランド
            %td
              テクエキ
          %tr
            %th
              商品の状態
            %td
              = @product.fresh_status
          %tr
            %th
              配送料の負担
            %td
              = @product.deliver_person
          %tr
            %th
              配送の方法
            %td
              = @product.deliver_way
          %tr
            %th
              配送元地域
            %td
              = link_to @product.from_area, "#"
          %tr
            %th
              発送日の目安
            %td
              = @product.deliver_leadtime

    .container__product-details__price
      %span.container__product-details__price__amount
        ¥
        = @product.price
      %span.container__product-details__price__tax
        (税込)
      %span.container__product-details__price__delivery-fee
        送料込み
    .container__product-details__message
      -if user_signed_in? && current_user.id == @product.user_id
        = link_to "商品の編集", edit_product_path, class: "submit-btn submit-btn-red"
        %p
          or
        = link_to "出品を再開する","", class: "submit-btn submit-btn-red"
        = link_to "この商品を削除する", product_path, class: "submit-btn submit-btn-gray", method: "DELETE"
      - elsif @product.sell_status == "出品中"
        .container__product-details__message__money
          売上金¥
          = rand(1000)
          とP
          = rand(1000)
          を
          %br
          お持ちです。
        = link_to "購入画面に進む", new_product_purchase_path(@product), class: "container__product-details__purchase-screen-button"
      - elsif @product.sell_status == "交渉中"
        = link_to "この商品は交渉中です", "", class: "submit-btn submit-btn-gray"
      - elsif @product.sell_status == "公開停止中"
        = link_to "この商品は公開停止中です", "", class: "submit-btn submit-btn-gray"
      - else
        = link_to "この商品の取引は完了しました", "", class: "submit-btn submit-btn-gray"
    .container__product-details__product-description
      %p.container__product-details__product-description__inner
        = simple_format @product.text
    .container__product-details__buttons
      .container__product-details__buttons__left
        %button.container__product-details__buttons__left__heart
          %i.far.fa-heart
          %span
            いいね!
          %span
            = rand (1000)
        %button.container__product-details__buttons__left__report
          %i.far.fa-flag
          %span
            不適切な商品の報告

      .container__product-details__buttons__right
        = link_to "" do
          %i.fas.fa-lock
          %span
            あんしん・あんぜんへの取り組み

  .container__comment
    .container__comment__container
      %form.container__comment__container__message-form
        %p.container__comment__container__message-form__attention
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea.container__comment__container__message-form__text
        %button.container__comment__container__message-form__comment-btn
          %span
            コメントする

  %ul.container__product-link
    %li.container__product-link__prev
      = link_to "" do
        %i.fas.fa-chevron-left
        前の商品
    %li.container__product-link__next
      = link_to "" do
        次の商品
        %i.fas.fa-chevron-right
        
  .container__social-media
    %ul.container__social-media__box
      %li.container__social-media__box__facebook
        = link_to "" do
          %i.fab.fa-facebook-square.fa-3x
      %li.container__social-media__box__twitter
        = link_to "" do
          %i.fab.fa-twitter-square.fa-3x
      %li.container__social-media__box__line
        = link_to "" do
          %i.fab.fa-line.fa-3x
      %li.container__social-media__box__pinterest
        = link_to "" do
          %i.fab.fa-pinterest-square.fa-3x

  .container__other-products
    .container__other-products__login-user
      %h2.container__other-products__login-user__title
        = link_to "#{@product.user.nickname}さんのその他の出品", ""
      .container__other-products__login-user__products
        - @product.user.products.where(sell_status: "出品中").each do |product|
          .container__other-products__login-user__products__product
            = link_to "/products/#{product.id}", class:"container__other-products__login-user__products__product__link" do
              %figure.container__other-products__login-user__products__product__link__image
                = image_tag product.product_images.find_by(product_id: product.id).image_url, size:"220x220"
              .container__other-products__login-user__products__product__link__body
                %h3.container__other-products__login-user__products__product__link__body__name
                  = product.title
                .container__other-products__login-user__products__product__link__body__num
                  .container__other-products__login-user__products__product__link__body__num__price
                    ¥
                    = product.price
                  .container__other-products__login-user__products__product__link__body__num__heart
                    %i.far.fa-heart
                    %span
                      = rand(1000)

    .container__other-products__same-category
      %h2.container__other-products__same-category__title
        = link_to "カテゴリ その他の出品", ""
      .container__other-products__same-category__products
        - @products.each do |product|
          .container__other-products__same-category__products__product
            = link_to product_path(product.id), class:".container__other-products__same-category__products__product__link" do
              %figure.container__other-products__same-category__products__product__link__image
                = image_tag src= product.product_images.first.image_url, size: "220x220"
              .container__other-products__same-category__products__product__link__body
                %h3.container__other-products__same-category__products__product__link__body__name
                  = product.title
                .container__other-products__same-category__products__product__link__body__num
                  .container__other-products__same-category__products__product__link__body__num__price
                    ¥
                    = product.price

  %navi.container__bread-crumbs
    %ul.container__bread-crumbs__list
      %li.container__bread-crumbs__list__mercari
        = link_to root_path do
          メルカリ
          %i.fas.fa-chevron-right
      %li.container__bread-crumbs__list__current-product
        %span
          = @product.title
          
%footer
  =render "layouts/footer-advertisement"
  %nav
  = render "layouts/footer-black"