config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
  end
  
  # ユーザー
  resources 'users', except: [:edit] do
    collection do
      get 'credit_register'
      get 'edit'
      get 'logout'
      get 'edit_profile'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'mercaris#index'

  # products
  resources 'products' do
    resources 'purchase' ,only: [:new,:create,:index]
    collection do
      get 'purchase_confirmation'
      get 'products/bigcategory'   => 'products#bigcategory',   defaults:{format: 'json'}
      get 'products/smallcategory' => 'products#smallcategory', defaults:{format: 'json'}
      get 'products/size'          => 'products#size',          defaults:{format: 'json'}
    end
  end

  # search
  resources 'search',only: :index

  resources :signin ,only: [:new,:create,:index]


  resources :signup ,only: [:index,:create] do
    collection do
      get 'registration'
      post 'registration' => 'signup#first_validation'
      get 'sms_authentication' 
      post 'sms_authentication' => 'signup#sms_post'
      get 'sms_confirmation' 
      post 'sms_confirmation' => 'signup#sms_check'
      get 'address' 
      post 'address' => 'signup#second_validation'
      get 'creditcard'
      get 'done'
    end
  end
end

app/views/layouts/_bottom-camera.html.haml
.bottom-camera
  %p 出品
  = link_to new_product_path do
    %i.fa.fa-camera

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs
  .breadcrumbs__wrapper
    .breadcrumbs__wrapper__content
      = link_to root_path do
        メルカリ
      %ul
        %li
          %i.fa.fa-chevron-right
          %span
            = yield :current_page

app/views/layouts/_footer-advertisement.html.haml
.advertisement
  .advertisement__box
    .advertisement__box__left
      .advertisement__box__left__description
        スマホでかんたんフリマアプリ
      .advertisement__box__left__reminder
        今すぐ無料ダウンロード！
      .advertisement__box__left__logos
        .advertisement__box__left__logos__mercari
          = image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/mercari_icon-f75780e32e41e052c8aaa8b446331cd8.png"
        .advertisement__box__left__logos__appstore
          .dvertisement__box__left__logos__appstore__image
            = link_to "#" do
              = image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg"
        .advertisement__box__left__logos__google
          .advertisement__box__left__logos__google__image
            = link_to "#" do
              = image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg"
    .advertisement__box__image
    = image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/download_app_pc-a4418175e8be071827ac88d073f40e4a.png", size: "300x260"

app/views/layouts/_footer-black.html.haml
%footer.footer
  .footer__top
    .footer__top__about.footer-content
      %h2 メルカリについて
      %ul
        %li
          = link_to "#" do
            会社概要（運営会社）
        %li
          = link_to "#" do
            採用情報
        %li
          = link_to "#" do
            プレスリリース
        %li
          = link_to "#" do
            公式ブログ
        %li
          = link_to "#" do
            メルカリロゴ利用ガイドライン
        %li.sns
          = link_to "#" do
            %i.fab.fa-twitter
          = link_to "#" do
            %i.fab.fa-facebook
    .footer__top__helpguide.footer-content
      %h2 ヘルプ＆ガイド
      %ul
        %li
          = link_to "#" do
            メルカリガイド
        %li
          = link_to "#" do
            らくらくメルカリ便
        %li
          = link_to "#" do
            ゆうゆうメルカリ便
        %li
          = link_to "#" do
            大型メルカリ便
        %li
          = link_to "#" do
            車体取引ガイド
        %li
          = link_to "#" do
            メルカリあんしん・あんぜん宣言！
        %li
          = link_to "#" do
            偽ブランド品撲滅への取り組み
        %li
          = link_to "#" do
            メルカリボックス
    .footer__top__privacy-law.footer-content
      %h2 プライバシーと利用規約
      .footer__top__privacy-law__wrapper
        .footer__top__privacy-law__wrapper__privacy
          %ul
            %li
              = link_to "#" do
                プライバシーポリシー
            %li
              = link_to "#" do
                メルカリ利用規約
            %li
              = link_to "#" do
                あんしんスマホサポート制度に関する利用特約
            %li
              = link_to "#" do
                コンプライアンスポリシー
        .footer__top__privacy-law__wrapper__law
          %ul
            %li
              = link_to "#" do
                個人データの安全管理に係る基本方針
            %li
              = link_to "#" do
                特定商取引に関する表記
            %li
              = link_to "#" do
                資金決済法に基づく表示
            %li
              = link_to "#" do
                法令遵守と犯罪抑止のために
    .footer__top__country.footer-content
      %h2 国
      %ul
        %li
          = link_to "#" do
            日本
        %li
          = link_to "#" do
            United States
  .footer__bottom
    .footer__bottom__logo
      = link_to root_path do
        = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?2482339763"
    .footer__bottom__copyright
      %span © 2019 Mercari

app/views/layouts/_main-header.html.haml
%header
  .box
    .box__top
      .box__top__title
        = link_to root_path do
          = image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg", size: "134x36"
      .box__top__search
        = form_for @form, url: search_index_path,method: :get,html: {class: "box__top__search__form"} do |f|
          = f.text_field :keyword,{placeholder: "何かお探しですか？", class: "box__top__search__form__input"}
          = f.button type: "submit",class: "search-btn" do
            %i.fas.fa-search

    .box__lower
      .box__lower__left
        .box__lower__left__category
          = link_to class: "" do
            %i.fas.fa-list-ul
            カテゴリーから探す
          .box__lower__left__category__wrapper
            %ul.category_box.category_index_box
              - @categories.each do |category|
                %li{class:"category_#{category.id} category_#{category.id}_red"}
                  = category.name
              %li
                カテゴリ一覧
            %ul.category_box.bigcategory_box
              - @bigcategories.each do |bigcategory|
                %li{class:"category_#{bigcategory.category_index_id} bigcategory_#{bigcategory.id} bigcategory_#{bigcategory.id}_gray"}
                  = bigcategory.name
            %ul.category_box.smallcategory_box
              - @smallcategories.each do |smallcategory|
                %li{class:"bigcategory_#{smallcategory.bigcategory_id}"}
                  = smallcategory.name
        .box__lower__left__brand
          = link_to class: "" do
            %i.fas.fa-tag
            ブランドから探す
      .box__lower__right
        %ul.box__lower__right__list
          - if user_signed_in?
            %li.box__lower__right__list__notice
              = link_to class: "" do
                %i.far.fa-bell
                お知らせ
            %li.box__lower__right__list__todo
              = link_to class: "" do
                %i.fas.fa-check
                やることリスト
            %li.box__lower__right__list__mypage
              = link_to user_path(current_user),class: "" do
                = image_tag src="https://static.mercdn.net/images/member_photo_noimage_thumb.png", size: "134x36"
                マイページ
          - else
            %li.box__lower__right__list__signup
              = link_to signup_index_path,class: "submit-btn submit-btn-red header-registration-btn" do
                新規会員登録
            %li.box__lower__right__list__sigin
              = link_to signin_index_path,class: "submit-btn header-registration-btn header-signin-btn" do
                ログイン
  

app/views/layouts/_user-navi.html.haml
.user-mypage-wrapper__navi
  .user-mypage-wrapper__navi__menu
    %ul
      %li
        = link_to "/users/#{current_user.id}" ,class:"link" do
          マイページ
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_notice_path", class:"link" do
          お知らせ
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage-tasks_path", class:"link" do
          やることリスト
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage-good-index_path", class:"link" do
          いいね！一覧
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to new_product_path, class:"link" do
          出品する
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_sell_index",class:"link" do
          出品した商品-出品中
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_sell_trading",class:"link" do
          出品した商品-取引中
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_sell_sold",class:"link" do
          出品した商品-売却済み
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_buy_trading",class:"link" do
          購入した商品-取引中
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_buy_past",class:"link" do
          購入した商品-過去の取引
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_news_index",class:"link" do
          ニュース一覧
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_reliable",class:"link" do
          評価一覧
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_guide",class:"link" do
          ガイド
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "mypage_contact",class:"link" do
          お問い合わせ
          %i.fas.fa-chevron-right.menu-icon
  .user-mypage-wrapper__navi__merpay
    %h3 メルペイ
    %ul
      %li
        = link_to "merpay_apply",class:"link" do
          売上・振込申請
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "merpay_points",class:"link" do
          ポイント
          %i.fas.fa-chevron-right.menu-icon
  .user-mypage-wrapper__navi__config
    %h3 設定
    %ul 
      %li
        = link_to edit_profile_users_path,class:"link" do
          プロフィール
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "config_address",class:"link" do
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to credit_register_users_path,class:"link" do
          支払い方法
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "config_mail",class:"link" do
          メール/パスワード
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to edit_users_path ,class:"link" do
          本人情報
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to "config_telephone",class:"link" do
          電話番号の確認
          %i.fas.fa-chevron-right.menu-icon
      %li
        = link_to logout_users_path,class:"link" do
          ログアウト          
          %i.fas.fa-chevron-right.menu-icon

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample58a
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}/
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
    %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.2.0/css/all.css", integrity: "sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ", rel: "stylesheet"}/
  %body
    = yield

app/views/layouts/form_layout.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %link{href: "https://use.fontawesome.com/releases/v5.0.6/css/all.css", rel: "stylesheet"}/
    %title 
      = content_for?(:html_title) ? yield(:html_title) : "FreemarketSample58a" 
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'load'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'load'
  %body.simple-form
    = yield